Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: main
      CodeUri: /Users/berkan/Repositories/berkan/csense-monorepo/apps/demo-parser
      Runtime: go1.x
      Architectures:
        - x86_64